<a href="https://colab.research.google.com/github/nistaku/TMDL/blob/main/Progress_Report_Week2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd

# Housing Price

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Course/Bechelor1/Block4/TMDL/Week1/home-data-for-ml-course/train.csv")
df

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0        1          60       RL         65.0     8450   Pave   NaN      Reg   
1        2          20       RL         80.0     9600   Pave   NaN      Reg   
2        3          60       RL         68.0    11250   Pave   NaN      IR1   
3        4          70       RL         60.0     9550   Pave   NaN      IR1   
4        5          60       RL         84.0    14260   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1455  1456          60       RL         62.0     7917   Pave   NaN      Reg   
1456  1457          20       RL         85.0    13175   Pave   NaN      Reg   
1457  1458          70       RL         66.0     9042   Pave   NaN      Reg   
1458  1459          20       RL         68.0     9717   Pave   NaN      Reg   
1459  1460          20       RL         75.0     9937   Pave   NaN      Reg   

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
2            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
3            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
4            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
...          ...       ...  ...      ...    ...    ...         ...     ...   
1455         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1456         Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
1457         Lvl    AllPub  ...        0    NaN  GdPrv        Shed    2500   
1458         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1459         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   

     MoSold YrSold  SaleType  SaleCondition  SalePrice  
0         2   2008        WD         Normal     208500  
1         5   2007        WD         Normal     181500  
2         9   2008        WD         Normal     223500  
3         2   2006        WD        Abnorml     140000  
4        12   2008        WD         Normal     250000  
...     ...    ...       ...            ...        ...  
1455      8   2007        WD         Normal     175000  
1456      2   2010        WD         Normal     210000  
1457      5   2010        WD         Normal     266500  
1458      4   2010        WD         Normal     142125  
1459      6   2008        WD         Normal     147500  

[1460 rows x 81 columns]

# Chest X-Ray Images

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import cv2

# Load color image (BGR format by default in OpenCV)
img = cv2.imread("/content/drive/MyDrive/Course/Bechelor1/Block4/TMDL/Week2/IM-0001-0001.jpeg")

# Convert BGR to RGB (for compatibility with Matplotlib/PIL)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
img_array = np.array('/content/drive/MyDrive/Course/Bechelor1/Block4/TMDL/Week2/IM-0001-0001.jpeg')  # Convert to NumPy array
print(img)  # Output: (height, width, channels)

[[[ 0  0  0]
  [32 32 32]
  [33 33 33]
  ...
  [33 33 33]
  [34 34 34]
  [ 0  0  0]]

 [[ 0  0  0]
  [33 33 33]
  [33 33 33]
  ...
  [34 34 34]
  [34 34 34]
  [ 0  0  0]]

 [[ 1  1  1]
  [33 33 33]
  [33 33 33]
  ...
  [34 34 34]
  [34 34 34]
  [ 0  0  0]]

 ...

 [[ 0  0  0]
  [28 28 28]
  [28 28 28]
  ...
  [34 34 34]
  [35 35 35]
  [ 0  0  0]]

 [[ 0  0  0]
  [29 29 29]
  [28 28 28]
  ...
  [34 34 34]
  [35 35 35]
  [ 0  0  0]]

 [[ 0  0  0]
  [29 29 29]
  [29 29 29]
  ...
  [35 35 35]
  [34 34 34]
  [ 0  0  0]]]
